##Get todas las movies

GET http://localhost:1234/movies

###GET una movie

GET  http://localhost:1234/movies/8c820c34-5f4b-11ef-95c4-c4e984dd9cb2

###GET Obtener todas las movies por genero

GET  http://localhost:1234/movies?genre=Drama


###POST Almacenar movie

POST http://localhost:1234/movies
content-type: application/json

{
    "sql":"Select * from movies",
    "title": "Spiderman",
    "year": 1997,
    "director": "James Cameron",
    "duration": 195,
    "poster": "https://i.pinimg.com/originals/42/42/65/4242658e6f1b0d6322a4a93e0383108b.png",
    "genre": [
      "Drama",
      "Romance"
    ],
    "rate":9.5
}

###Actualizar la pelicula
PATCH http://localhost:1234/movies/8c820c34-5f4b-11ef-95c4-c4e984dd9cb2
content-type: application/json

{
  "title": "Spiderman II",
  "year": 1998,
  "director": "James Cameron",
  "duration": 200,
  "poster": "https://i.pinimg.com/originals/42/42/65/4242658e6f1b0d6322a4a93e0383108b.png",
  "rate": 9.5
}

###Eliminar movie
DELETE http://localhost:1234/movies/6e35570a-5f4b-11ef-95c4-c4e984dd9cb2
content-type: application/json 